application: levr-production
version: 2
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"

handlers:
- url: /
  script: landing.app
- url: /terms
  script: terms.app
- url: /ninjas
  script: ninjas.app
- url: /phone.*
  script: phone.app
- url: /merchants.*
  script: merchants.app
- url: /new.*
  script: test_class.app
  login: admin
- url: /loginstate
  script: loginstate.app
- url: /logout
  script: logout.app
- url: /emptySet.*
  script: emptySet.app
  login: admin
- url: /admin.*
  script: admin.app
  login: admin
- url: /payments/.*
  script: payments.app
  login: admin
  secure: always
- url: /sandbox
  script: test.app
  login: admin
- url: /password.*
  script: password.app
- url: /widget.*
  script: widget.app
- url: /_ah/mail/.+
  #mail services
  script: uploadEmail.app
  login: admin
- url: /target.*
  login: admin
  script: store_businesses.app
- url: /download.*
  script: download.app
- url: /beta.*
  script: beta.app
- url: /foursquare.*
  script: foursquare.app
  secure: always
- url: /facebook.*
  script: facebook.app
- url: /mobile.*
  script: mobile.app
#  secure: always

#tasks and cronjobs
- url: /tasks.*
  script: tasks.app
  login: admin
- url: /cronjobs.*
  script: cron_jobs.app
  login: admin
  
  
#begin API scripts
- url: /api/deal.*
  script: api_deal.app
- url: /api/upload.*
  script: api_upload.app
- url: /api/search.*
  script: api_search.app
- url: /api/user.*
  script: api_user.app
- url: /api/signup.*
  script: api_signup.app
- url: /api/login.*
  script: api_login.app
- url: /api/connect.*
  script: api_connect.app
- url: /api/merchant.*
  script: api_merchant.app
- url: /api/deeplink.*
  script: api_deeplink.app



- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /beta
  static_dir: beta

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /.*
  #share handler - alphanumeric appendage
  script: share.app
- url: .*
  script: landing.app
  
libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.3

builtins:
- appstats: on
- deferred: on

inbound_services:
- mail


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^boto/
- ^Crypto/
